### ISSUE TITLE
How to run demo?

### ISSUE THREAD

**Issue by coolandsmartrr** [forgojs/forgo-examples#1]
Sorry, I am not very familiar with node.js web dev, and am struggling to run the code examples.

I ran `npm install` and `npm start`, which gave me the following error log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.10
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle forgo-examples@~prestart: forgo-examples@
6 info lifecycle forgo-examples@~start: forgo-examples@
7 verbose lifecycle forgo-examples@~start: unsafe-perm in lifecycle true
8 verbose lifecycle forgo-examples@~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/ricky/Documents/Github/forgo-examples/node_modules/.bin:/Users/ricky/.rbenv/shims:/Users/ricky/.rbenv/bin:/Users/ricky/.cargo/bin:/Users/ricky/Library/Python/3.8/bin:/Users/ricky/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/opt/X11/bin:/Library/Apple/usr/bin
9 verbose lifecycle forgo-examples@~start: CWD: /Users/ricky/Documents/Github/forgo-examples
10 silly lifecycle forgo-examples@~start: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'rm -rf dist/ && cp -r public/ dist/ && parcel public/index.html'
10 silly lifecycle ]
11 info lifecycle forgo-examples@~start: Failed to exec start script
12 verbose stack Error: forgo-examples@ start: `rm -rf dist/ && cp -r public/ dist/ && parcel public/index.html`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose pkgid forgo-examples@
14 verbose cwd /Users/ricky/Documents/Github/forgo-examples
15 verbose Darwin 19.6.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v12.18.2
18 verbose npm  v6.14.10
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error forgo-examples@ start: `rm -rf dist/ && cp -r public/ dist/ && parcel public/index.html`
23 error spawn ENOENT
24 error Failed at the forgo-examples@ start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

How can I resolve this issue and run the examples successfully?

**Comment by jeswin** [comment]
Let me try to help you. 

You needed to install parcel earlier. (parceljs.org)

```
npm install -g parcel-bundler
```

But if you pull the latest, you shouldn't have to install it globally. But you'll have to do an ```npm install``` again, so that you get the latest dependencies.

**Comment by jeswin** [comment]
After that, you could run one of the three examples:

```sh
npm run start
npm run start-todos
npm run start-routing
```

**Comment by coolandsmartrr** [comment]
Thank you!

**Comment by coolandsmartrr** [comment]
#2 This modification should help others when running examples.

**Comment by jeswin** [comment]
I've merged your changes. Made a small edit as well: you don't require parcel-bundler to be globally installed any more. Just 'npm install' should work.

Once you can confirm that these changes are working for you, you could close this issue.

**Comment by coolandsmartrr** [comment]
Thank you, it works!
